apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: open-cluster-management-argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.12.2
    helm:
      releaseName: metrics-server
      values: |-
        args:
          - --kubelet-insecure-tls
        replicas: 2
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
