apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-internal
  namespace: spms-live-dev
spec:
  project: default
  destination:
    server: https://172.18.255.200:443?agentName=spms-live-dev # Replace with https://<principal-external-ip:port>?agentName=<managed-cluster-name>
    namespace: ingress-nginx-internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.1
    helm:
      releaseName: ingress-nginx-internal
      parameters:
        - name: controller.replicaCount
          value: "3"
        - name: controller.service.external.externalTrafficPolicy
          value: "Local"
        - name: controller.ingressClassResource.name
          value: "nginx-internal"
        - name: controller.ingressClassResource.controllerValue
          value: "k8s.io/ingress-nginx-internal"
        - name: controller.ingressClassResource.enabled
          value: "true"
        - name: controller.ingressClassByName
          value: "true"
        - name: controller.ingressClassResource.default
          value: "false"
        - name: controller.ingressClass
          value: "internal"
        - name: controller.service.loadBalancerIP
          value: "172.18.255.210"
